\input texinfo @c -*-texinfo-*-
@c %**start of header
@c
@c Visa Single Sign-on System
@c Copyright (C) 2011 Bindle Binaries <syzdek@bindlebinaries.com>.
@c
@c @BINDLE_BINARIES_BSD_LICENSE_START@
@c
@c Redistribution and use in source and binary forms, with or without
@c modification, are permitted provided that the following conditions are
@c met:
@c
@c    * Redistributions of source code must retain the above copyright
@c      notice, this list of conditions and the following disclaimer.
@c    * Redistributions in binary form must reproduce the above copyright
@c      notice, this list of conditions and the following disclaimer in the
@c      documentation and/or other materials provided with the distribution.
@c    * Neither the name of Bindle Binaries nor the
@c      names of its contributors may be used to endorse or promote products
@c      derived from this software without specific prior written permission.
@c
@c THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
@c IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
@c THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
@c PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL BINDLE BINARIES BE LIABLE FOR
@c ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
@c DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
@c SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
@c CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
@c LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
@c OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
@c SUCH DAMAGE.
@c
@c @BINDLE_BINARIES_BSD_LICENSE_END@
@c
@c doc/readme.texi - provides overview of VISA
@c

@setfilename readme.info
@settitle README

@c For double-sided printing, uncomment:
@c @setchapternewpage odd
@c %**end of header

@include version-readme.texi

@ifclear titlePageLoaded
@include titlepage.texi
@end ifclear

@setchapternewpage off

@ifnottex
@node Top 
@top README
@menu
* About: README About.
@end menu
@end ifnottex 

@node README About
@chapter About

Blah Blah Blah


@bye
